package admin;



	import javax.swing.JPanel;
	import javax.swing.GroupLayout.Alignment;
	import javax.swing.GroupLayout;
	import java.awt.Color;
	import javax.swing.JLabel;
	import javax.swing.ImageIcon;
	import java.awt.Font;
	import javax.swing.LayoutStyle.ComponentPlacement;

import login.Login;

import java.awt.FlowLayout;
	import javax.swing.JButton;
	import javax.swing.JSpinner;
	import java.awt.event.ActionListener;
	import java.util.Timer;
	import java.awt.event.ActionEvent;
	import java.awt.event.MouseAdapter;
	import java.awt.event.MouseEvent;

	public class RegisterUsers extends javax.swing.JFrame {
	    /**
	     * Creates new form Home
	     */
	    public RegisterUsers() {
	    	getContentPane().setBackground(Color.BLACK);
	    	
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {
	    	setUndecorated(true);
	    	//setBounds(100, 100, 1250, 600);
	    	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        
	        JPanel panel = new JPanel();
	        panel.setBackground(new Color(0, 0, 128));
	        
	        JPanel panel_2 = new JPanel();
	        panel_2.setLayout(null);
	        panel_2.setBackground(new Color(0, 0, 128));
	        
	        JLabel lblNewLabel_2_2 = new JLabel("");
	        lblNewLabel_2_2.setBounds(1200, 8, 58, 48);
	        panel_2.add(lblNewLabel_2_2);
	        
	        JLabel lblNewLabel_3_2 = new JLabel();
	        lblNewLabel_3_2.setForeground(Color.WHITE);
	        lblNewLabel_3_2.setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
	        lblNewLabel_3_2.setBounds(1250, 29, 74, 14);
	        panel_2.add(lblNewLabel_3_2);
	        
	        JPanel panel_1 = new JPanel();
	        panel_1.setBackground(Color.BLACK);
	        FlowLayout flowLayout = (FlowLayout) panel_1.getLayout();
	        flowLayout.setHgap(0);
	        flowLayout.setAlignment(FlowLayout.LEFT);
	        flowLayout.setAlignOnBaseline(true);
	        
	        JPanel panel_1_1 = new JPanel();
	        panel_1_1.setBackground(Color.BLACK);
	        
	        JPanel panel_1_2 = new JPanel();
	        panel_1_2.setBackground(Color.BLACK);
	        
	        JButton btnNewButton_3_1 = new JButton("Upload Images");
	        btnNewButton_3_1.addActionListener(new ActionListener() {
	        	public void actionPerformed(ActionEvent e) {
	        		setVisible(false);
	        		   images object = new images();
	                   object.setVisible(true);
	        	}
	        });
	        btnNewButton_3_1.setForeground(Color.WHITE);
	        btnNewButton_3_1.setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
	        btnNewButton_3_1.setBackground(Color.BLACK);
	        
	        JButton btnNewButton_3_1_1 = new JButton("Register Courses");
	        btnNewButton_3_1_1.addActionListener(new ActionListener() {
	        	public void actionPerformed(ActionEvent e) {
	        		setVisible(false);
	        		register_courses object = new register_courses();
	                   object.setVisible(true);
	        	}
	        });
	        btnNewButton_3_1_1.setForeground(Color.WHITE);
	        btnNewButton_3_1_1.setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
	        btnNewButton_3_1_1.setBackground(Color.BLACK);
	        
	        JButton btnNewButton_3 = new JButton("Courses");
	        btnNewButton_3.addActionListener(new ActionListener() {
	        	public void actionPerformed(ActionEvent e) {
	        		 setVisible(false);
	                 courses object = new courses();
	                 object.setVisible(true);
	        	}
	        });
	        btnNewButton_3.setForeground(new Color(255, 255, 255));
	        btnNewButton_3.setBackground(new Color(0, 0, 0));
	        btnNewButton_3.setFont(new Font("Segoe UI Semilight", Font.BOLD, 14));

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        layout.setHorizontalGroup(
	        	layout.createParallelGroup(Alignment.TRAILING)
	        		.addComponent(panel, GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
	        		.addGroup(layout.createSequentialGroup()
	        			.addComponent(panel_2, GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
	        			.addContainerGap())
	        		.addGroup(layout.createSequentialGroup()
	        			.addGap(68)
	        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
	        				.addComponent(panel_1_1, GroupLayout.PREFERRED_SIZE, 189, GroupLayout.PREFERRED_SIZE)
	        				.addComponent(btnNewButton_3))
	        			.addPreferredGap(ComponentPlacement.RELATED)
	        			.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
	        				.addGroup(layout.createSequentialGroup()
	        					.addComponent(btnNewButton_3_1_1)
	        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        					.addComponent(btnNewButton_3_1))
	        				.addGroup(layout.createSequentialGroup()
	        					.addComponent(panel_1, GroupLayout.PREFERRED_SIZE, 134, GroupLayout.PREFERRED_SIZE)
	        					.addPreferredGap(ComponentPlacement.UNRELATED)
	        					.addComponent(panel_1_2, GroupLayout.PREFERRED_SIZE, 177, GroupLayout.PREFERRED_SIZE)))
	        			.addContainerGap(35, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	        	layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(layout.createSequentialGroup()
	        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
	        			.addPreferredGap(ComponentPlacement.RELATED, 18, GroupLayout.PREFERRED_SIZE)
	        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
	        				.addComponent(panel_1_2, GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
	        				.addComponent(panel_1, GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
	        				.addComponent(panel_1_1, GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
	        			.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
	        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        				.addComponent(btnNewButton_3_1_1, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
	        				.addComponent(btnNewButton_3_1, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
	        				.addComponent(btnNewButton_3))
	        			.addGap(23)
	        			.addComponent(panel_2, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE))
	        );
	        
	        JButton btnNewButton_4 = new JButton("Back");
	        btnNewButton_4.setBounds(251, 9, 112, 34);
	        panel_2.add(btnNewButton_4);
	        btnNewButton_4.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\logout.png"));
	        btnNewButton_4.addActionListener(new ActionListener() {
	        	public void actionPerformed(ActionEvent e) {
	        		   setVisible(false);
	        		   AdminDashboard object = new AdminDashboard();
	                   object.setVisible(true);
	        	}
	        });
	        btnNewButton_4.setForeground(Color.WHITE);
	        btnNewButton_4.setFont(new Font("Segoe UI Semilight", Font.BOLD, 14));
	        btnNewButton_4.setBackground(new Color(0, 0, 0));
	        
	        JLabel lblNewLabel_6 = new JLabel("");
	        lblNewLabel_6.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\configuration.png"));
	        panel_1_2.add(lblNewLabel_6);
	        
	        
	        JButton btnNewButton_2 = new JButton("Register Admin");
	        btnNewButton_2.setForeground(new Color(255, 255, 255));
	        btnNewButton_2.setBackground(new Color(0, 0, 0));
	        btnNewButton_2.setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
	        btnNewButton_2.addActionListener(new ActionListener() {
	        	
	        	
	        	public void actionPerformed(ActionEvent e) {
	        		
	        		 setVisible(false);
        			 admRegister object = new admRegister();
        	            object.setVisible(true);
	        		
	        	}
	        });
	        panel_1_2.add(btnNewButton_2);
	        
	        JLabel lblNewLabel_5 = new JLabel("");
	        lblNewLabel_5.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\AddStudent.png"));
	        panel_1_1.add(lblNewLabel_5);
	        
	        JButton btnNewButton_1 = new JButton("Register Student!");
	        btnNewButton_1.setBackground(new Color(0, 0, 0));
	        btnNewButton_1.setForeground(new Color(255, 255, 255));
	        btnNewButton_1.addActionListener(new ActionListener() {
	        	public void actionPerformed(ActionEvent e) {
	        		setVisible(false);
		            stuRegister object = new stuRegister();
		            object.setVisible(true);
	        	}
	        });
	        btnNewButton_1.setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
	        panel_1_1.add(btnNewButton_1);
	        panel_1_1.setBounds(400,45,42,466);
	        
	        JLabel lblNewLabel_4 = new JLabel("");
	        lblNewLabel_4.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\addAdmin.png"));
	        panel_1.add(lblNewLabel_4);
	        
	        JButton btnNewButton = new JButton("Register Lecturer");
	        btnNewButton.setBackground(new Color(0, 0, 0));
	        btnNewButton.addActionListener(new ActionListener() {
	        	public void actionPerformed(ActionEvent e) {
	        		 setVisible(false);
	                  LecRegister reg = new LecRegister();
	                  reg.setVisible(true);
	        	}
	        });
	        btnNewButton.setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
	        btnNewButton.setForeground(new Color(255, 255, 255));
	        panel_1.add(btnNewButton);
	        panel.setLayout(null);
	        
	        JLabel lblNewLabel = new JLabel("");
	        lblNewLabel.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\Employee\\INTACT ABODE\\Images\\edit.png"));
	        lblNewLabel.setBounds(37, 24, 41, 32);
	        panel.add(lblNewLabel);
	        
	        JLabel lblNewLabel_1 = new JLabel("Register New User!");
	        lblNewLabel_1.setForeground(Color.WHITE);
	        lblNewLabel_1.setFont(new Font("Segoe UI Semilight", Font.BOLD, 25));
	        lblNewLabel_1.setBounds(70, 12, 238, 44);
	        panel.add(lblNewLabel_1);
	        
	        JLabel lblNewLabel_2 = new JLabel("");
	        lblNewLabel_2.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\Employee\\icons\\male_user_50px.png"));
	        lblNewLabel_2.setBounds(1200, 8, 58, 48);
	        panel.add(lblNewLabel_2);
	        
	        JLabel lblNewLabel_3 = new JLabel("Welcome!");
	        lblNewLabel_3.setFont(new Font("Segoe UI Semilight", Font.BOLD, 12));
	        lblNewLabel_3.setForeground(Color.WHITE);
	        lblNewLabel_3.setBounds(1250, 29, 74, 14);
	        panel.add(lblNewLabel_3);
	        getContentPane().setLayout(layout);

	        pack();
	    }// </editor-fold>                        

	    /**
	     * @param args the command line arguments
	     */
	    public static void main(String args[]) {
	        /* Set the Nimbus look and feel */
	        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	         */
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(RegisterUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(RegisterUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(RegisterUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(RegisterUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>

	        /* Create and display the form */
	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                //new RegisterStu().setVisible(true);
	            	RegisterUsers registerStu = new RegisterUsers();
	                registerStu.setVisible(true);
	                registerStu.setLocationRelativeTo(null);
	                
	            }
	        });
	    }		
}
