
package admin;

import chart.ModelCard;


import chart.ModelChart;
import login.Login;

import java.awt.Color;
import java.awt.Font;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import javax.swing.JLabel;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.awt.event.ActionEvent;

/**
 *
 * @author RAVEN
 */
public class AdminDashboard extends javax.swing.JFrame {
	  private String currentCourseCode = "";

    /**
     * Creates new form Main
     */
    public AdminDashboard() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        initData();
    }

    private void initData() {
        LocalDate currentDate = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        String formattedDate = currentDate.format(formatter);

        // Variables to hold data
        int totalStudents = 0;

        try {
            // Establish a connection to the database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/attendancedb", "root", "");

            // Create a statement
            Statement stmt = conn.createStatement();

            // Execute a query to count the total number of students
            String studentQuery = "SELECT COUNT(*) AS total FROM student";
            ResultSet studentRs = stmt.executeQuery(studentQuery);

            // Process the result set
            if (studentRs.next()) {
                totalStudents = studentRs.getInt("total");
            }

            // Execute a query to fetch a course code from the timetable
            String courseQuery = "SELECT course_code FROM timetable LIMIT 2";
            ResultSet courseRs = stmt.executeQuery(courseQuery);

            // Process the result set
            if (courseRs.next()) {
                currentCourseCode = courseRs.getString("course_code");
            }

            // Close the connection
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Calculate current week based on semester start and end dates
        int currentWeek = calculateCurrentWeek();
    }

    private int calculateCurrentWeek() {
        try {
            // Establish a connection to the database
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/attendancedb", "root", "");

            // Create a statement
            Statement stmt = conn.createStatement();

            // Execute a query to fetch semester start and end dates
            String query = "SELECT semester_start, semester_end FROM admin";
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                LocalDate semesterStart = rs.getDate("semester_start").toLocalDate();
                LocalDate semesterEnd = rs.getDate("semester_end").toLocalDate();
                
                // Calculate current week based on current date and semester start
                long daysBetween = ChronoUnit.DAYS.between(semesterStart, LocalDate.now());
                int currentWeek = (int) (daysBetween / 7) + 1;

                // Close the connection
                conn.close();

                return currentWeek;
            }

            // Close the connection
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return 0; // Default return value if calculation fails
    }

    

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
    	   
    	
    	

        panel1 = new Panel();
        panel2 = new Panel1();

    

        panel1.setBackground(new Color(0, 0, 0));
        panel1.setForeground(new Color(0, 0, 0));

        panel2.setBackground(new Color(0, 0, 0));
        panel2.setForeground(new Color(0, 0, 102));
        
        Panel1 panel_3 = new Panel1();
        panel_3.setForeground(new Color(0, 0, 128));
        panel_3.setBackground(new Color(0, 0, 0));
        
        Panel1 panel_4 = new Panel1();
        panel_4.setForeground(new Color(0, 0, 128));
        panel_4.setBackground(new Color(0, 0, 0));
        
        Panel1 panel_5 = new Panel1();
        panel_5.setForeground(new Color(0, 0, 128));
        panel_5.setBackground(new Color(0, 0, 0));
        
        Panel1 panel_6 = new Panel1();
        panel_6.setForeground(new Color(0, 0, 128));
        panel_6.setBackground(new Color(0, 0, 0));
        
        Panel1 panel_7 = new Panel1();
        panel_7.setForeground(new Color(0, 0, 128));
        panel_7.setBackground(new Color(0, 0, 0));
        
        Panel1 panel_8 = new Panel1();
        panel_8.setForeground(new Color(0, 0, 128));
        panel_8.setBackground(new Color(0, 0, 0));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2Layout.setHorizontalGroup(
        	panel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panel2Layout.createSequentialGroup()
        			.addGap(34)
        			.addGroup(panel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(panel_3, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE)
        				.addComponent(panel_6, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE))
        			.addGap(79)
        			.addGroup(panel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(panel_4, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE)
        				.addComponent(panel_7, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
        			.addGroup(panel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(panel_5, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE)
        				.addComponent(panel_8, GroupLayout.PREFERRED_SIZE, 258, GroupLayout.PREFERRED_SIZE))
        			.addGap(130))
        );
        panel2Layout.setVerticalGroup(
        	panel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, panel2Layout.createSequentialGroup()
        			.addGroup(panel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(Alignment.LEADING, panel2Layout.createSequentialGroup()
        					.addGap(31)
        					.addComponent(panel_5, GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(panel_8, GroupLayout.PREFERRED_SIZE, 246, GroupLayout.PREFERRED_SIZE))
        				.addGroup(panel2Layout.createSequentialGroup()
        					.addContainerGap(31, Short.MAX_VALUE)
        					.addGroup(panel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(panel2Layout.createSequentialGroup()
        							.addComponent(panel_4, GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(panel_7, GroupLayout.PREFERRED_SIZE, 245, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED))
        						.addGroup(Alignment.TRAILING, panel2Layout.createSequentialGroup()
        							.addComponent(panel_3, GroupLayout.PREFERRED_SIZE, 247, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(panel_6, GroupLayout.PREFERRED_SIZE, 246, GroupLayout.PREFERRED_SIZE)))))
        			.addGap(24))
        );
        
        JLabel lblNewLabel_7 = new JLabel("");
        lblNewLabel_7.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\showAdmin.png"));
        panel_8.add(lblNewLabel_7);
        
        JButton btnRegisterStudent_1_1_1 = new JButton("Register Courses");
        btnRegisterStudent_1_1_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		 setVisible(false);
                 courses object = new courses();
                 object.setVisible(true);
        	}
        });
        btnRegisterStudent_1_1_1.setForeground(new Color(255, 255, 255));
        btnRegisterStudent_1_1_1.setFont(new Font("Segoe UI Semilight", Font.BOLD, 16));
        btnRegisterStudent_1_1_1.setBackground(new Color(0, 0, 128));
        panel_8.add(btnRegisterStudent_1_1_1);
        
        JLabel lblNewLabel_5 = new JLabel("");
        panel_7.add(lblNewLabel_5);
        
        JLabel lblNewLabel_6 = new JLabel("");
        lblNewLabel_6.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\showStudent.png"));
        panel_7.add(lblNewLabel_6);
        
        JButton btnRegisterStudent_1_1 = new JButton("Upload Images");
        btnRegisterStudent_1_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		setVisible(false);
     		   images object = new images();
                object.setVisible(true);
        	}
        });
        btnRegisterStudent_1_1.setForeground(new Color(255, 255, 255));
        btnRegisterStudent_1_1.setFont(new Font("Segoe UI Semilight", Font.BOLD, 16));
        btnRegisterStudent_1_1.setBackground(new Color(0, 0, 128));
        panel_7.add(btnRegisterStudent_1_1);
        
        JLabel lblNewLabel_4 = new JLabel("");
        lblNewLabel_4.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\configuration1.png"));
        panel_6.add(lblNewLabel_4);
        
        JButton btnRegisterStudent_1 = new JButton("Create/Update Courses");
        btnRegisterStudent_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		setVisible(false);
        		register_courses object = new register_courses();
                   object.setVisible(true);
        		}
        });
        btnRegisterStudent_1.setForeground(new Color(255, 255, 255));
        btnRegisterStudent_1.setFont(new Font("Segoe UI Semilight", Font.BOLD, 16));
        btnRegisterStudent_1.setBackground(new Color(0, 0, 128));
        panel_6.add(btnRegisterStudent_1);
        
        JLabel lblNewLabel_1_1 = new JLabel("");
        panel_6.add(lblNewLabel_1_1);
        
        JLabel lblNewLabel_3 = new JLabel("");
        lblNewLabel_3.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\configuration.png"));
        panel_5.add(lblNewLabel_3);
        
        JButton btnNewButton_5 = new JButton("Register Admin");
        btnNewButton_5.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		 setVisible(false);
    			 admRegister object = new admRegister();
    	            object.setVisible(true);
        	}
        });
        btnNewButton_5.setForeground(new Color(255, 255, 255));
        btnNewButton_5.setBackground(new Color(0, 0, 128));
        btnNewButton_5.setFont(new Font("Segoe UI Semilight", Font.BOLD, 16));
        panel_5.add(btnNewButton_5);
        
        JLabel lblNewLabel_2 = new JLabel("");
        lblNewLabel_2.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\addAdmin.png"));
        panel_4.add(lblNewLabel_2);
        
        JButton btnNewButton_4 = new JButton("Register Lecturer");
        btnNewButton_4.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		 setVisible(false);
                 LecRegister reg = new LecRegister();
                 reg.setVisible(true);
        	}
        });
        btnNewButton_4.setBackground(new Color(0, 0, 128));
        btnNewButton_4.setFont(new Font("Segoe UI Semilight", Font.BOLD, 16));
        btnNewButton_4.setForeground(new Color(255, 255, 255));
        panel_4.add(btnNewButton_4);
        
        JLabel lblNewLabel_1 = new JLabel("");
        lblNewLabel_1.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\AddStudent.png"));
        panel_3.add(lblNewLabel_1);
        
        JButton btnRegisterStudent = new JButton("Register Student!");
        btnRegisterStudent.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		setVisible(false);
	            stuRegister object = new stuRegister();
	            object.setVisible(true);
        	}
        });
        btnRegisterStudent.setForeground(new Color(255, 255, 255));
        btnRegisterStudent.setBackground(new Color(0, 0, 128));
        btnRegisterStudent.setFont(new Font("Segoe UI Semilight", Font.BOLD, 16));
        panel_3.add(btnRegisterStudent);
        panel2.setLayout(panel2Layout);
        
        panel = new Panel();
        panel.setForeground(new Color(0, 0, 102));
        panel.setBackground(new Color(0, 0, 0));
        
        JLabel home = new JLabel();
        home.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\home.png"));
        home.setBounds(22, 16, 80, 32);
        panel.add(home);
        
        JLabel adminLabel = new JLabel("Admin Dashboard");
        adminLabel.setForeground(Color.WHITE);
        adminLabel.setFont(new Font("Segoe UI Semibold", Font.BOLD, 35));
        adminLabel.setBounds(70, 12, 250, 28);
        panel.add(adminLabel);
        
        
        
        Panel1 panel_1 = new Panel1();
        panel_1.setForeground(new Color(0, 0, 128));
        panel_1.setBackground(new Color(0, 0, 0));
        
        imageAvatar1 = new admin.ImageAvatar();
   	    imageAvatar1.setBackground(new java.awt.Color(102, 51, 255));
        imageAvatar1.setGradientColor1(new java.awt.Color(71, 61, 255));
        imageAvatar1.setGradientColor2(new java.awt.Color(211, 236, 6));
        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/admin/p1.jpg")));          
                     
       panel_1.add(imageAvatar1);    	
        
       JPanel panel_2 = new JPanel();
        panel_2.setForeground(new Color(0, 0, 102));
        panel_2.setBackground(new Color(0, 0, 0));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1Layout.setHorizontalGroup(
        	panel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(panel, GroupLayout.DEFAULT_SIZE, 1314, Short.MAX_VALUE)
        		.addGroup(panel1Layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(panel_1, GroupLayout.PREFERRED_SIZE, 178, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(panel2, GroupLayout.PREFERRED_SIZE, 1102, GroupLayout.PREFERRED_SIZE)
        			.addGap(18))
        		.addGroup(Alignment.TRAILING, panel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(panel_2, GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE)
        			.addContainerGap())
        );
        panel1Layout.setVerticalGroup(
        	panel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panel1Layout.createSequentialGroup()
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(panel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(panel2, 0, 0, Short.MAX_VALUE)
        				.addComponent(panel_1, GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(panel_2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addContainerGap())
        );
        
        JButton btnNewButton_3 = new JButton("Log out");
        btnNewButton_3.setFont(new Font("Segoe UI Semilight", Font.BOLD, 16));
        btnNewButton_3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		setVisible(false);
                Login object = new Login();
                object.setVisible(true);
        	}
        });
        btnNewButton_3.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\logout.png"));
        btnNewButton_3.setForeground(new Color(255, 255, 255));
        btnNewButton_3.setBackground(new Color(0, 0, 0));
        panel_2.add(btnNewButton_3);
        
        btnNewButton_2 = new JButton("View Users");
        btnNewButton_2.setFont(new Font("Segoe UI Semilight", Font.BOLD, 14));
        btnNewButton_2.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\google_forms_24px.png"));
        btnNewButton_2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		setVisible(false);
                Users object = new Users();
                object.setVisible(true);
        	}
        });
        btnNewButton_2.setForeground(new Color(255, 255, 255));
        btnNewButton_2.setBackground(new Color(0, 0, 0));
        panel_1.add(btnNewButton_2);
        
        btnNewButton = new JButton("View Attendance");
        btnNewButton.setFont(new Font("Segoe UI Semilight", Font.BOLD, 14));
        btnNewButton.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\date.png"));
        btnNewButton_2.setIcon(new javax.swing.ImageIcon("C:\\Users\\PARADISE\\Desktop\\Employee\\icons\\google_forms_24px.png"));
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		setVisible(false);
                ViewAttendance object = new ViewAttendance();
                object.setVisible(true);
        	}
        });
        btnNewButton.setBackground(new Color(0, 0, 0));
        btnNewButton.setForeground(new Color(255, 255, 255));
        panel_1.add(btnNewButton);
        
        btnTimetable = new JButton("Create Timetable");
        btnTimetable.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\sort_window_24px.png"));
        btnTimetable.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		setVisible(false);
	            timetable object = new timetable();
	            object.setVisible(true);
        	}
        });
        btnTimetable.setForeground(Color.WHITE);
        btnTimetable.setFont(new Font("Segoe UI Semilight", Font.BOLD, 14));
        btnTimetable.setBackground(new Color(0, 0, 0));
        panel_1.add(btnTimetable);
        
        JLabel lblNewLabel = new JLabel("");
        panel_1.add(lblNewLabel);
        
        JButton btnNewButton_1 = new JButton("Take Attendance");
        btnNewButton_1.setIcon(new ImageIcon("C:\\Users\\PARADISE\\Desktop\\sgele\\YEAR IV\\Project\\AttendanceSystem\\icon\\bell_26px.png"));
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		 setVisible(false);
                 run object = new run();
                 object.setVisible(true);
        	}
        });
        btnNewButton_1.setBackground(new Color(0, 0, 0));
        btnNewButton_1.setForeground(new Color(255, 255, 255));
        btnNewButton_1.setFont(new Font("Segoe UI Semilight", Font.BOLD, 16));
        panel_1.add(btnNewButton_1);
        panel1.setLayout(panel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     //   chart.start();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }
    private Panel panel1;
    private Panel1 panel2;
    private Panel panel;
    private Panel panel_1;
    private JButton btnNewButton;
    private JButton btnNewButton_2;
    private Panel panel_2;
    private ImageAvatar imageAvatar1;
    private JButton btnTimetable;
    private JPanel panel_4;
    private JPanel panel_5;
    private JPanel panel_6;
    private JPanel panel_7;
    private JPanel panel_8;
}
